insert into clients (name) values ('Jabbersphere');
insert into clients (name) values ('Browsecat');
insert into clients (name) values ('Pixoboo');
insert into clients (name) values ('Dynabox');
insert into clients (name) values ('Meevee');
insert into clients (name) values ('Gabtype');
insert into clients (name) values ('Oozz');
insert into clients (name) values ('Flashpoint');
insert into clients (name) values ('Jabbertype');
insert into clients (name) values ('Voonix');
insert into clients (name) values ('Oyoyo');
insert into clients (name) values ('Chatterpoint');
insert into clients (name) values ('Shuffletag');
insert into clients (name) values ('Buzzshare');
insert into clients (name) values ('Fivebridge');
insert into clients (name) values ('Wordpedia');
insert into clients (name) values ('Dynava');
insert into clients (name) values ('Yata');
insert into clients (name) values ('Quatz');
insert into clients (name) values ('Edgetag');

insert into users (roles, username, firstName, lastName, email, password, sex, position) values ('[\"user\"]','zmayler0', 'Zonda', 'Mayler', 'a@a.com', '$2b$10$LUKIS8nCMsRb4oKVqa5RR.w3rZUUr7.JZ0rZaXiZOEu0r7F7v6Aku', 'F', 'clarithromycin');
insert into users (roles, username, firstName, lastName, email, password, sex, position) values ('[\"user\"]','ccamp1', 'Cordey', 'Camp', 'b@a.com', '$2b$10$LUKIS8nCMsRb4oKVqa5RR.w3rZUUr7.JZ0rZaXiZOEu0r7F7v6Aku', 'F', 'TIGAN');
insert into users (roles, username, firstName, lastName, email, password, sex, position) values ('[\"user\"]','lmassie2', 'Letta', 'Massie', 'c@a.com', '$2b$10$LUKIS8nCMsRb4oKVqa5RR.w3rZUUr7.JZ0rZaXiZOEu0r7F7v6Aku', 'F', 'Ampicillin and Sulbactam');
insert into users (roles, username, firstName, lastName, email, password, sex, position) values ('[\"user\"]','gcrilly3', 'Gerladina', 'Crilly', 'gcrilly3@springer.com', '$2b$10$LUKIS8nCMsRb4oKVqa5RR.w3rZUUr7.JZ0rZaXiZOEu0r7F7v6Aku', 'F', 'stimulant laxative enteric coated');
insert into users (roles, username, firstName, lastName, email, password, sex, position) values ('[\"user\"]','clangstone4', 'Constantino', 'Langstone', 'clangstone4@seattletimes.com', '$2b$10$LUKIS8nCMsRb4oKVqa5RR.w3rZUUr7.JZ0rZaXiZOEu0r7F7v6Aku', 'M', 'Methocarbamol');
insert into users (roles, username, firstName, lastName, email, password, sex, position) values ('[\"user\"]','jfeatherstonhaugh5', 'Jasmina', 'Featherstonhaugh', 'jfeatherstonhaugh5@weibo.com', '$2b$10$LUKIS8nCMsRb4oKVqa5RR.w3rZUUr7.JZ0rZaXiZOEu0r7F7v6Aku', 'F', 'MICONAZOLE');
insert into users (roles, username, firstName, lastName, email, password, sex, position) values ('[\"user\"]','rshouler6', 'Roselle', 'Shouler', 'rshouler6@wikipedia.org', '$2b$10$LUKIS8nCMsRb4oKVqa5RR.w3rZUUr7.JZ0rZaXiZOEu0r7F7v6Aku', 'F', 'HYZAAR');
insert into users (roles, username, firstName, lastName, email, password, sex, position) values ('[\"user\"]','vchristofle7', 'Velvet', 'Christofle', 'vchristofle7@friendfeed.com', '$2b$10$LUKIS8nCMsRb4oKVqa5RR.w3rZUUr7.JZ0rZaXiZOEu0r7F7v6Aku', 'F', 'Sodium Chloride');
insert into users (roles, username, firstName, lastName, email, password, sex, position) values ('[\"user\"]','mwicher8', 'Mariette', 'Wicher', 'mwicher8@lycos.com', '$2b$10$LUKIS8nCMsRb4oKVqa5RR.w3rZUUr7.JZ0rZaXiZOEu0r7F7v6Aku', 'F', 'LISINOPRIL AND HYDROCHLOROTHIAZIDE');
insert into users (roles, username, firstName, lastName, email, password, sex, position) values ('[\"user\"]','rpay9', 'Rayna', 'Pay', 'rpay9@npr.org', '$2b$10$LUKIS8nCMsRb4oKVqa5RR.w3rZUUr7.JZ0rZaXiZOEu0r7F7v6Aku', 'F', 'Sertraline hydrochloride');
insert into users (roles, username, firstName, lastName, email, password, sex, position) values ('[\"user\"]','bsharplinga', 'Bennie', 'Sharpling', 'bsharplinga@huffingtonpost.com', '$2b$10$LUKIS8nCMsRb4oKVqa5RR.w3rZUUr7.JZ0rZaXiZOEu0r7F7v6Aku', 'F', 'topcare headache formula');
insert into users (roles, username, firstName, lastName, email, password, sex, position) values ('[\"user\"]','tsouthwardb', 'Tim', 'Southward', 'tsouthwardb@aboutads.info', '$2b$10$LUKIS8nCMsRb4oKVqa5RR.w3rZUUr7.JZ0rZaXiZOEu0r7F7v6Aku', 'M', 'Lipitor');
insert into users (roles, username, firstName, lastName, email, password, sex, position) values ('[\"user\"]','cdavorenc', 'Carlene', 'Davoren', 'cdavorenc@harvard.edu', '$2b$10$LUKIS8nCMsRb4oKVqa5RR.w3rZUUr7.JZ0rZaXiZOEu0r7F7v6Aku', 'F', 'SEROQUEL');
insert into users (roles, username, firstName, lastName, email, password, sex, position) values ('[\"user\"]','gclyburnd', 'Gage', 'Clyburn', 'gclyburnd@list-manage.com', '$2b$10$LUKIS8nCMsRb4oKVqa5RR.w3rZUUr7.JZ0rZaXiZOEu0r7F7v6Aku', 'M', 'RUE 21 Young Strawberry');
insert into users (roles, username, firstName, lastName, email, password, sex, position) values ('[\"user\"]','mgatsbye', 'Michaeline', 'Gatsby', 'mgatsbye@independent.co.uk', '$2b$10$LUKIS8nCMsRb4oKVqa5RR.w3rZUUr7.JZ0rZaXiZOEu0r7F7v6Aku', 'F', 'Pulmo Ferrum');
insert into users (roles, username, firstName, lastName, email, password, sex, position) values ('[\"user\"]','jbauchopf', 'Joe', 'Bauchop', 'jbauchopf@miitbeian.gov.cn', '$2b$10$LUKIS8nCMsRb4oKVqa5RR.w3rZUUr7.JZ0rZaXiZOEu0r7F7v6Aku', 'M', 'Celeragesic');
insert into users (roles, username, firstName, lastName, email, password, sex, position) values ('[\"user\"]','kcrowleyg', 'Kevon', 'Crowley', 'kcrowleyg@howstuffworks.com', '$2b$10$LUKIS8nCMsRb4oKVqa5RR.w3rZUUr7.JZ0rZaXiZOEu0r7F7v6Aku', 'M', 'Triamcinolone Acetonide');
insert into users (roles, username, firstName, lastName, email, password, sex, position) values ('[\"user\"]','rcordaroyh', 'Ruby', 'Cordaroy', 'rcordaroyh@umn.edu', '$2b$10$LUKIS8nCMsRb4oKVqa5RR.w3rZUUr7.JZ0rZaXiZOEu0r7F7v6Aku', 'F', 'Divigel');
insert into users (roles, username, firstName, lastName, email, password, sex, position) values ('[\"user\"]','pmctavishi', 'Pacorro', 'McTavish', 'pmctavishi@nymag.com', '$2b$10$LUKIS8nCMsRb4oKVqa5RR.w3rZUUr7.JZ0rZaXiZOEu0r7F7v6Aku', 'M', 'ProState Relief');
insert into users (roles, username, firstName, lastName, email, password, sex, position) values ('[\"user\"]','dtoshj', 'Darcy', 'Tosh', 'dtoshj@parallels.com', '$2b$10$LUKIS8nCMsRb4oKVqa5RR.w3rZUUr7.JZ0rZaXiZOEu0r7F7v6Aku', 'M', 'Painazol Pain Relief');

insert into projects (name, ClientId, createdById) values ('Ntags', 1, 2);
insert into projects (name, ClientId, createdById) values ('Avamba', 8, 14);
insert into projects (name, ClientId, createdById) values ('Vipe', 4, 2);
insert into projects (name, ClientId, createdById) values ('Ntag', 14, 9);
insert into projects (name, ClientId, createdById) values ('Leenti', 6, 10);
insert into projects (name, ClientId, createdById) values ('Centimia', 4, 1);
insert into projects (name, ClientId, createdById) values ('Chatterbridge', 3, 15);
insert into projects (name, ClientId, createdById) values ('Youfeed', 6, 18);
insert into projects (name, ClientId, createdById) values ('Youtags', 17, 2);
insert into projects (name, ClientId, createdById) values ('Topdrive', 4, 8);
insert into projects (name, ClientId, createdById) values ('Brightdog', 7, 5);
insert into projects (name, ClientId, createdById) values ('LiveZ', 20, 13);
insert into projects (name, ClientId, createdById) values ('Devbug', 5, 2);
insert into projects (name, ClientId, createdById) values ('Zoombox', 20, 20);
insert into projects (name, ClientId, createdById) values ('Thoughtstorm', 11, 10);
insert into projects (name, ClientId, createdById) values ('Tavu', 10, 8);
insert into projects (name, ClientId, createdById) values ('Blogspan', 13, 19);
insert into projects (name, ClientId, createdById) values ('Edgeify', 9, 2);
insert into projects (name, ClientId, createdById) values ('Aimbu', 1, 13);
insert into projects (name, ClientId, createdById) values ('Gigabox', 9, 12);

insert into `ProjectStages` (`id`, `name`, `order`, `projectId`) values (null, 'todo', '1', '1');
insert into `ProjectStages` (`id`, `name`, `order`, `projectId`) values (null, 'test', '2', '1');
insert into `ProjectStages` (`id`, `name`, `order`, `projectId`) values (null, 'deploy', '3', '1');
insert into `ProjectStages` (`id`, `name`, `order`, `projectId`) values (null, 'complete', '4', '1');
insert into `ProjectStages` (`id`, `name`, `order`, `projectId`) values (null, 'todo', '1', '3');
insert into `ProjectStages` (`id`, `name`, `order`, `projectId`) values (null, 'test', '2', '3');
insert into `ProjectStages` (`id`, `name`, `order`, `projectId`) values (null, 'complete', '3', '3');
insert into `ProjectStages` (`id`, `name`, `order`, `projectId`) values (null, 'todo', '1', '2');
insert into `ProjectStages` (`id`, `name`, `order`, `projectId`) values (null, 'test', '2', '2');
insert into `ProjectStages` (`id`, `name`, `order`, `projectId`) values (null, 'complete', '3', '2');

insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Tachybaptus ruficollis', 'Puncture wound w/o foreign body of right breast, init encntr', 1, 4, '2021-03-26 11:26:10', 1, 11, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Deroptyus accipitrinus', 'Unsp superfic inj right eyelid and perioculr area, init', 4, 5, '2020-10-02 07:28:05', 9, 6, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Eremophila alpestris', 'Puncture wound w/o foreign body of finger w damage to nail', 5, 1, '2020-11-18 01:04:21', 20, 9, 1);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Pituophis melanaleucus', 'Lac w/o fb of abd wall, periumb rgn w penet perit cav, init', 4, 5, '2020-08-15 19:50:55', 6, 2, 1);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Rhea americana', 'Unsp inj unsp musc/fasc/tend at forarm lv, right arm, subs', 2, 1, '2020-12-01 01:31:21', 10, 17, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Larus dominicanus', 'Unspecified injury of right forearm, sequela', 2, 1, '2021-01-22 22:41:19', 7, 20, 2);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Columba livia', 'Laceration of extensor musc/fasc/tend thmb at wrs/hnd lv', 5, 1, '2021-04-07 05:51:34', 15, 5, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Ictalurus furcatus', 'Newborn small for gestational age, 1750-1999 grams', 1, 5, '2021-01-31 05:12:08', 19, 16, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Damaliscus lunatus', 'Contus/lac cereb, w LOC of 30 minutes or less, subs', 4, 2, '2021-03-16 10:47:56', 11, 1, 4);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Junonia genoveua', 'Bacterial infection, unspecified', 4, 2, '2020-06-02 06:25:27', 20, 4, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Lutra canadensis', 'Recurrent dislocation, right knee', 1, 1, '2021-01-18 02:32:47', 6, 19, 2);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('unavailable', 'Malignant neoplasm of female genital organ, unspecified', 5, 1, '2021-02-16 19:53:57', 7, 7, 5);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Diomedea irrorata', 'Temporal sclerosis', 3, 5, '2020-11-26 11:20:41', 11, 5, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Francolinus swainsonii', 'Breakdown of prosthetic orbit of right eye, sequela', 5, 2, '2020-09-23 05:05:15', 3, 5, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Echimys chrysurus', 'Fall due to controlled fire, not in bldg, init', 1, 1, '2021-02-23 19:33:47', 11, 7, 3);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Varanus sp.', 'Corrosion of first degree of male genital region, subs', 2, 3, '2020-08-04 22:45:15', 4, 8, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Ornithorhynchus anatinus', 'Oth comp of spinal and epidural anesth during preg, unsp tri', 5, 3, '2020-10-10 09:06:28', 11, 3, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Phoca vitulina', 'Displacmnt of implnt elec nstim of spinal cord lead, sequela', 1, 3, '2021-04-28 09:58:10', 14, 9, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Canis mesomelas', 'Breakdown of cranial or spinal infusion catheter, subs', 2, 2, '2020-07-26 22:15:34', 16, 7, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Lemur catta', 'Toxic effect of alcohol', 4, 3, '2020-12-24 09:05:42', 16, 2, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Semnopithecus entellus', 'Central dislocation of left hip, initial encounter', 2, 2, '2020-11-27 02:04:52', 2, 14, 8);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Lemur catta', 'Lesion of lateral popliteal nerve, unspecified lower limb', 5, 4, '2020-08-02 04:04:47', 20, 5, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Uraeginthus bengalus', 'Subluxation of left ankle joint, sequela', 2, 2, '2020-09-01 07:50:17', 1, 19, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Gyps bengalensis', 'Neoplasm of uncertain behavior of right kidney', 2, 2, '2021-04-27 21:26:52', 4, 20, 6);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Macropus eugenii', 'Corrosion of third degree of forehead and cheek', 4, 3, '2021-02-24 23:18:06', 2, 20, 20);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Bassariscus astutus', 'Laceration of blood vessel of right middle finger, init', 1, 2, '2020-06-29 02:54:11', 1, 7, 18);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Equus burchelli', 'Unspecified injury of dorsal vein of left foot, init encntr', 3, 5, '2021-05-10 00:41:50', 20, 6, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Phasianus colchicus', 'Puncture wound without foreign body, right thigh, sequela', 2, 5, '2021-05-12 15:07:57', 12, 4, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Bettongia penicillata', 'Disorders of urea cycle metabolism', 4, 3, '2020-10-05 13:44:18', 5, 10, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Canis lupus', 'Ped on rolr-skt injured in clsn w rail trn/veh nontraf, init', 5, 1, '2020-12-23 11:44:06', 15, 5, 8);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Larus fuliginosus', 'Laceration without foreign body of anus, initial encounter', 1, 1, '2020-09-04 07:59:29', 2, 16, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Numida meleagris', 'Strain flexor musc/fasc/tend r rng fngr at forarm lv, subs', 4, 1, '2020-09-11 16:42:47', 19, 20, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Estrilda erythronotos', 'Sickle-cell thalassemia with acute chest syndrome', 4, 4, '2020-11-23 01:42:56', 6, 3, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Pycnonotus barbatus', 'Oth soft tissue disorders related to use/pressure, unsp hand', 3, 3, '2020-05-28 18:44:05', 10, 16, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Elephas maximus bengalensis', 'Foreign body on external eye, part unspecified, left eye', 2, 2, '2020-12-02 09:16:13', 9, 11, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Lemur catta', 'Donors of organs and tissues', 3, 2, '2021-01-16 00:11:15', 19, 2, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Mephitis mephitis', 'Unsp intracap fx unsp femr, 7thE', 1, 1, '2020-12-22 12:24:14', 17, 3, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Eutamias minimus', 'Unspecified diabetes mellitus in the puerperium', 2, 4, '2021-01-24 03:00:13', 19, 20, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Geochelone elephantopus', 'Unspecified atrophy of edentulous alveolar ridge', 2, 3, '2021-04-24 08:58:21', 12, 4, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Tockus erythrorhyncus', 'Laceration of bronchus, unspecified', 4, 3, '2021-04-03 22:34:11', 17, 13, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Paradoxurus hermaphroditus', 'Toxic effect of aflatoxin', 1, 2, '2020-07-28 01:57:15', 7, 3, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Dasypus septemcincus', 'Stress fracture, hip, unsp, subs for fx w malunion', 3, 3, '2021-05-21 22:19:26', 17, 11, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Amblyrhynchus criprojectStageId', 'Superficial foreign body, left lesser toe(s)', 1, 4, '2021-02-13 09:33:43', 20, 6, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Acrobates pygmaeus', 'Generalized contraction of visual field', 4, 3, '2020-10-23 14:35:42', 19, 6, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Cordylus giganteus', 'Unsp superficial injury of unsp part of head, subs encntr', 2, 5, '2020-08-16 23:14:44', 15, 2, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Smithopsis crassicaudata', 'Oth dis of bld/bld-form org/immun mechnsm comp preg,unsp tri', 2, 4, '2020-10-13 01:33:15', 8, 5, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Macropus giganteus', 'Adverse effect of unsp drugs aff the autonomic nervous sys', 4, 2, '2020-10-01 09:16:38', 7, 6, 12);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Dusicyon thous', 'Local-rel symptc epi w simp prt seiz,not ntrct, w/o stat epi', 3, 2, '2020-12-26 03:44:36', 10, 13, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Tockus flavirostris', 'Bathroom in school dormitory as place', 1, 2, '2021-02-05 22:14:16', 7, 12, null);
insert into tasks (title, description, projectStageId, priority, deadline, createdById, projectId, parentId) values ('Ictonyx striatus', 'Malignant neoplasm of central nervous system, unspecified', 2, 4, '2020-08-26 11:23:24', 20, 18, null);

insert into TaskComments (text, userId, taskId) values ('Ben neo paraganglia NEC', 8, 32);
insert into TaskComments (text, userId, taskId) values ('Undet circ-fall residenc', 18, 32);
insert into TaskComments (text, userId, taskId) values ('Jt derangment NOS-up/arm', 17, 8);
insert into TaskComments (text, userId, taskId) values ('Adhesive pericarditis', 12, 17);
insert into TaskComments (text, userId, taskId) values ('Dissem intravasc coag NB', 14, 50);
insert into TaskComments (text, userId, taskId) values ('No vaccin-immune comp', 10, 27);
insert into TaskComments (text, userId, taskId) values ('Ac margin ulc w perf-obs', 20, 35);
insert into TaskComments (text, userId, taskId) values ('Breech present-antepart', 17, 29);
insert into TaskComments (text, userId, taskId) values ('Ac bulbar polio-type NOS', 8, 49);
insert into TaskComments (text, userId, taskId) values ('Burn NOS multiple site', 16, 45);
insert into TaskComments (text, userId, taskId) values ('Sprain metacarpophalang', 5, 22);
insert into TaskComments (text, userId, taskId) values ('Lack norm physio dev NOS', 12, 21);
insert into TaskComments (text, userId, taskId) values ('Merkel cell ca-low limb', 5, 12);
insert into TaskComments (text, userId, taskId) values ('Dislocation patella-open', 20, 27);
insert into TaskComments (text, userId, taskId) values ('Cl skul base fx w/o coma', 2, 40);
insert into TaskComments (text, userId, taskId) values ('Comp-oth int ortho devic', 14, 3);
insert into TaskComments (text, userId, taskId) values ('Schizophrenia NOS-chr', 1, 28);
insert into TaskComments (text, userId, taskId) values ('Iodine hypothyroidism', 1, 36);
insert into TaskComments (text, userId, taskId) values ('Tularemia NOS', 6, 6);
insert into TaskComments (text, userId, taskId) values ('Hyperemia of conjunctiva', 1, 16);
insert into TaskComments (text, userId, taskId) values ('Myoglobinuria', 20, 46);
insert into TaskComments (text, userId, taskId) values ('Mgrn wo aura w ntrc mgrn', 10, 38);
insert into TaskComments (text, userId, taskId) values ('Keratoconjunctivit sicca', 12, 41);
insert into TaskComments (text, userId, taskId) values ('Cervical root injury', 13, 8);
insert into TaskComments (text, userId, taskId) values ('Fx orbital floor-closed', 7, 48);
insert into TaskComments (text, userId, taskId) values ('Excessive attrition NOS', 12, 18);
insert into TaskComments (text, userId, taskId) values ('Mal neo ant 2/3 tongue', 20, 35);
insert into TaskComments (text, userId, taskId) values ('Herpes zoster of eyelid', 3, 46);
insert into TaskComments (text, userId, taskId) values ('Genital mutilation NOS', 9, 18);
insert into TaskComments (text, userId, taskId) values ('Ac cerebrovasc insuf NOS', 20, 7);
insert into TaskComments (text, userId, taskId) values ('Self inj-paintball gun', 7, 12);
insert into TaskComments (text, userId, taskId) values ('Lt ef oth paral dom side', 2, 21);
insert into TaskComments (text, userId, taskId) values ('Symbolic dysfunction NOS', 12, 36);
insert into TaskComments (text, userId, taskId) values ('Noninfect vag leukorrhea', 20, 22);
insert into TaskComments (text, userId, taskId) values ('TB of knee-cult dx', 17, 14);
insert into TaskComments (text, userId, taskId) values ('Postpart hem NEC-postpar', 18, 39);
insert into TaskComments (text, userId, taskId) values ('TB bronchiectasis-unspec', 9, 19);
insert into TaskComments (text, userId, taskId) values ('Encephalocele', 9, 6);
insert into TaskComments (text, userId, taskId) values ('Hyponasality', 19, 18);
insert into TaskComments (text, userId, taskId) values ('Aftrcare path fx arm NOS', 14, 15);
insert into TaskComments (text, userId, taskId) values ('Genetic torsion dystonia', 12, 39);
insert into TaskComments (text, userId, taskId) values ('Deep 3 deg burn palm', 5, 8);
insert into TaskComments (text, userId, taskId) values ('Proteinuria', 15, 12);
insert into TaskComments (text, userId, taskId) values ('Sec DM circ nt st uncntr', 9, 39);
insert into TaskComments (text, userId, taskId) values ('Salivary gland fistula', 6, 47);
insert into TaskComments (text, userId, taskId) values ('Traffic acc NOS-pers NOS', 19, 34);
insert into TaskComments (text, userId, taskId) values ('Schizo resid subchr/exac', 8, 45);
insert into TaskComments (text, userId, taskId) values ('Mv-oth veh coll-st car', 11, 18);
insert into TaskComments (text, userId, taskId) values ('Mal neo long bones arm', 12, 23);
insert into TaskComments (text, userId, taskId) values ('Spleen injury NOS-closed', 17, 20);
insert into TaskComments (text, userId, taskId) values ('Adv eff antmycob antbiot', 16, 46);
insert into TaskComments (text, userId, taskId) values ('Aircrft acc NEC-crew', 11, 34);
insert into TaskComments (text, userId, taskId) values ('Late effect leg fx', 12, 13);
insert into TaskComments (text, userId, taskId) values ('Candidal vulvovaginitis', 1, 45);
insert into TaskComments (text, userId, taskId) values ('Arthropathy w skin dis', 15, 40);
insert into TaskComments (text, userId, taskId) values ('Compl deliv NOS-postpart', 4, 19);
insert into TaskComments (text, userId, taskId) values ('Cns TB NOS-unspec', 11, 41);
insert into TaskComments (text, userId, taskId) values ('Sev nonprolf db retinoph', 4, 19);
insert into TaskComments (text, userId, taskId) values ('AMI anterolateral, init', 12, 21);
insert into TaskComments (text, userId, taskId) values ('Chr gouty atroph w tophi', 10, 33);
insert into TaskComments (text, userId, taskId) values ('Open wound thyroid-compl', 13, 9);
insert into TaskComments (text, userId, taskId) values ('Cholera carrier', 5, 42);
insert into TaskComments (text, userId, taskId) values ('Sexual precocity NEC', 9, 31);
insert into TaskComments (text, userId, taskId) values ('Lack norm physio dev NOS', 18, 2);
insert into TaskComments (text, userId, taskId) values ('Dislocat site NEC-open', 10, 49);
insert into TaskComments (text, userId, taskId) values ('Dysuria', 2, 45);
insert into TaskComments (text, userId, taskId) values ('Foreign body finger-inf', 3, 29);
insert into TaskComments (text, userId, taskId) values ('Schizophr dis resid-chr', 13, 2);
insert into TaskComments (text, userId, taskId) values ('Faucial diphtheria', 12, 13);
insert into TaskComments (text, userId, taskId) values ('Neurofibromatosis NEC', 2, 3);
insert into TaskComments (text, userId, taskId) values ('Adoles postural kyphosis', 9, 45);
insert into TaskComments (text, userId, taskId) values ('Hx-cong malform-gu', 4, 45);
insert into TaskComments (text, userId, taskId) values ('Obstruc/fet malpos-deliv', 2, 38);
insert into TaskComments (text, userId, taskId) values ('Inj deep plantar vessel', 15, 21);
insert into TaskComments (text, userId, taskId) values ('Perinatal condition NEC', 12, 2);
insert into TaskComments (text, userId, taskId) values ('War inj:blunt object', 17, 45);
insert into TaskComments (text, userId, taskId) values ('Leishmaniasis NOS', 19, 20);
insert into TaskComments (text, userId, taskId) values ('Abrasion foot/toe-infec', 16, 37);
insert into TaskComments (text, userId, taskId) values ('Horseshoe tear of retina', 10, 33);
insert into TaskComments (text, userId, taskId) values ('Hymenolepiasis', 5, 12);
insert into TaskComments (text, userId, taskId) values ('Tox eff nonmed subst NEC', 4, 39);
insert into TaskComments (text, userId, taskId) values ('Benign neo skin lip', 10, 34);
insert into TaskComments (text, userId, taskId) values ('Failure sterile surgery', 16, 35);
insert into TaskComments (text, userId, taskId) values ('Pathol dislocat-jt NEC', 7, 19);
insert into TaskComments (text, userId, taskId) values ('Gal&bil cal w/ac&ch w ob', 1, 46);
insert into TaskComments (text, userId, taskId) values ('Poison-ent preparation', 12, 43);
insert into TaskComments (text, userId, taskId) values ('Screening for rubella', 11, 38);
insert into TaskComments (text, userId, taskId) values ('Lung - kaposi''s sarcoma', 10, 44);
insert into TaskComments (text, userId, taskId) values ('Transient arterial occlu', 19, 33);
insert into TaskComments (text, userId, taskId) values ('Venezuelan equine fever', 19, 46);
insert into TaskComments (text, userId, taskId) values ('Accident in public bldg', 3, 10);
insert into TaskComments (text, userId, taskId) values ('Visual disturbances NEC', 8, 4);
insert into TaskComments (text, userId, taskId) values ('Mal neo lymph-head/neck', 7, 6);
insert into TaskComments (text, userId, taskId) values ('Fracture trunk bone-open', 4, 9);
insert into TaskComments (text, userId, taskId) values ('Spon ab w compl NOS-inc', 3, 30);
insert into TaskComments (text, userId, taskId) values ('Hx-intrathoracic mal NEC', 9, 32);
insert into TaskComments (text, userId, taskId) values ('Firearm accident NEC', 12, 28);
insert into TaskComments (text, userId, taskId) values ('Sprain interphalangeal', 1, 2);
insert into TaskComments (text, userId, taskId) values ('Post tp lymphprolif dis', 14, 29);
insert into TaskComments (text, userId, taskId) values ('Benign neo lymph nodes', 4, 7);

insert into TaskChecks (id, title, completed, solverId, taskId) values (1, 'Construction/Ag Equipment/Trucks', 0, 10, 2);
insert into TaskChecks (id, title, completed, solverId, taskId) values (2, 'n/a', 1, 3, 14);
insert into TaskChecks (id, title, completed, solverId, taskId) values (3, 'Semiconductors', 0, 5, 7);
insert into TaskChecks (id, title, completed, solverId, taskId) values (4, 'Water Supply', 0, 9, 1);
insert into TaskChecks (id, title, completed, solverId, taskId) values (5, 'n/a', 1, 4, 19);
insert into TaskChecks (id, title, completed, solverId, taskId) values (6, 'Power Generation', 1, 7, 2);
insert into TaskChecks (id, title, completed, solverId, taskId) values (7, 'Real Estate Investment Trusts', 1, 1, 2);
insert into TaskChecks (id, title, completed, solverId, taskId) values (8, 'Metal Fabrications', 0, 5, 11);
insert into TaskChecks (id, title, completed, solverId, taskId) values (9, 'n/a', 1, 5, 2);
insert into TaskChecks (id, title, completed, solverId, taskId) values (10, 'n/a', 0, 7, 2);
insert into TaskChecks (id, title, completed, solverId, taskId) values (11, 'Building operators', 0, 9, 19);
insert into TaskChecks (id, title, completed, solverId, taskId) values (12, 'Real Estate Investment Trusts', 0, 6, 17);
insert into TaskChecks (id, title, completed, solverId, taskId) values (13, 'Specialty Insurers', 1, 4, 9);
insert into TaskChecks (id, title, completed, solverId, taskId) values (14, 'Marine Transportation', 0, 6, 5);
insert into TaskChecks (id, title, completed, solverId, taskId) values (15, 'Clothing/Shoe/Accessory Stores', 0, 1, 17);
insert into TaskChecks (id, title, completed, solverId, taskId) values (16, 'Computer Software: Programming, Data Processing', 1, 1, 2);
insert into TaskChecks (id, title, completed, solverId, taskId) values (17, 'Coal Mining', 0, 1, 6);
insert into TaskChecks (id, title, completed, solverId, taskId) values (18, 'Catalog/Specialty Distribution', 1, 1, 7);
insert into TaskChecks (id, title, completed, solverId, taskId) values (19, 'Savings Institutions', 0, 1, 3);
insert into TaskChecks (id, title, completed, solverId, taskId) values (20, 'Computer Software: Prepackaged Software', 1, 8, 5);
insert into TaskChecks (id, title, completed, solverId, taskId) values (21, 'Biotechnology: Biological Products (No Diagnostic Substances)', 0, 2, 14);
insert into TaskChecks (id, title, completed, solverId, taskId) values (22, 'Major Banks', 1, 3, 13);
insert into TaskChecks (id, title, completed, solverId, taskId) values (23, 'Metal Fabrications', 1, 4, 11);
insert into TaskChecks (id, title, completed, solverId, taskId) values (24, 'n/a', 1, 9, 16);
insert into TaskChecks (id, title, completed, solverId, taskId) values (25, 'Major Pharmaceuticals', 1, 4, 13);
insert into TaskChecks (id, title, completed, solverId, taskId) values (26, 'Semiconductors', 1, 8, 20);
insert into TaskChecks (id, title, completed, solverId, taskId) values (27, 'n/a', 0, 7, 14);
insert into TaskChecks (id, title, completed, solverId, taskId) values (28, 'n/a', 0, 5, 13);
insert into TaskChecks (id, title, completed, solverId, taskId) values (29, 'Clothing/Shoe/Accessory Stores', 1, 8, 11);
insert into TaskChecks (id, title, completed, solverId, taskId) values (30, 'Property-Casualty Insurers', 0, 5, 7);
insert into TaskChecks (id, title, completed, solverId, taskId) values (31, 'Life Insurance', 0, 6, 6);
insert into TaskChecks (id, title, completed, solverId, taskId) values (32, 'Real Estate Investment Trusts', 1, 6, 19);
insert into TaskChecks (id, title, completed, solverId, taskId) values (33, 'Oil & Gas Production', 1, 1, 6);
insert into TaskChecks (id, title, completed, solverId, taskId) values (34, 'Electric Utilities: Central', 1, 9, 4);
insert into TaskChecks (id, title, completed, solverId, taskId) values (35, 'n/a', 0, 3, 7);
insert into TaskChecks (id, title, completed, solverId, taskId) values (36, 'Computer Software: Programming, Data Processing', 0, 3, 19);
insert into TaskChecks (id, title, completed, solverId, taskId) values (37, 'Package Goods/Cosmetics', 0, 5, 13);
insert into TaskChecks (id, title, completed, solverId, taskId) values (38, 'n/a', 1, 9, 16);
insert into TaskChecks (id, title, completed, solverId, taskId) values (39, 'Savings Institutions', 1, 3, 14);
insert into TaskChecks (id, title, completed, solverId, taskId) values (40, 'Clothing/Shoe/Accessory Stores', 1, 1, 5);
insert into TaskChecks (id, title, completed, solverId, taskId) values (41, 'Paints/Coatings', 1, 4, 15);
insert into TaskChecks (id, title, completed, solverId, taskId) values (42, 'EDP Services', 0, 8, 8);
insert into TaskChecks (id, title, completed, solverId, taskId) values (43, 'Biotechnology: Biological Products (No Diagnostic Substances)', 0, 2, 19);
insert into TaskChecks (id, title, completed, solverId, taskId) values (44, 'n/a', 0, 7, 2);
insert into TaskChecks (id, title, completed, solverId, taskId) values (45, 'Major Pharmaceuticals', 0, 9, 4);
insert into TaskChecks (id, title, completed, solverId, taskId) values (46, 'Radio And Television Broadcasting And Communications Equipment', 1, 7, 16);
insert into TaskChecks (id, title, completed, solverId, taskId) values (47, 'Power Generation', 1, 3, 9);
insert into TaskChecks (id, title, completed, solverId, taskId) values (48, 'Property-Casualty Insurers', 0, 2, 6);
insert into TaskChecks (id, title, completed, solverId, taskId) values (49, 'Electric Utilities: Central', 1, 4, 5);
insert into TaskChecks (id, title, completed, solverId, taskId) values (50, 'n/a', 0, 5, 1);
insert into TaskChecks (id, title, completed, solverId, taskId) values (51, 'Ophthalmic Goods', 1, 6, 2);
insert into TaskChecks (id, title, completed, solverId, taskId) values (52, 'Automotive Aftermarket', 1, 3, 13);
insert into TaskChecks (id, title, completed, solverId, taskId) values (53, 'Major Pharmaceuticals', 1, 3, 8);
insert into TaskChecks (id, title, completed, solverId, taskId) values (54, 'Real Estate Investment Trusts', 0, 1, 10);
insert into TaskChecks (id, title, completed, solverId, taskId) values (55, 'Major Pharmaceuticals', 0, 1, 13);
insert into TaskChecks (id, title, completed, solverId, taskId) values (56, 'Industrial Machinery/Components', 1, 4, 1);
insert into TaskChecks (id, title, completed, solverId, taskId) values (57, 'Electric Utilities: Central', 0, 1, 11);
insert into TaskChecks (id, title, completed, solverId, taskId) values (58, 'Containers/Packaging', 0, 9, 13);
insert into TaskChecks (id, title, completed, solverId, taskId) values (59, 'Ophthalmic Goods', 1, 9, 15);
insert into TaskChecks (id, title, completed, solverId, taskId) values (60, 'n/a', 0, 9, 11);
insert into TaskChecks (id, title, completed, solverId, taskId) values (61, 'Business Services', 1, 5, 3);
insert into TaskChecks (id, title, completed, solverId, taskId) values (62, 'Medical/Dental Instruments', 1, 1, 5);
insert into TaskChecks (id, title, completed, solverId, taskId) values (63, 'Oil & Gas Production', 1, 9, 15);
insert into TaskChecks (id, title, completed, solverId, taskId) values (64, 'Computer Software: Prepackaged Software', 0, 6, 9);
insert into TaskChecks (id, title, completed, solverId, taskId) values (65, 'n/a', 1, 10, 1);
insert into TaskChecks (id, title, completed, solverId, taskId) values (66, 'n/a', 1, 2, 10);
insert into TaskChecks (id, title, completed, solverId, taskId) values (67, 'Beverages (Production/Distribution)', 1, 2, 13);
insert into TaskChecks (id, title, completed, solverId, taskId) values (68, 'n/a', 1, 2, 18);
insert into TaskChecks (id, title, completed, solverId, taskId) values (69, 'n/a', 1, 6, 18);
insert into TaskChecks (id, title, completed, solverId, taskId) values (70, 'n/a', 1, 10, 4);
insert into TaskChecks (id, title, completed, solverId, taskId) values (71, 'Oil & Gas Production', 0, 8, 3);
insert into TaskChecks (id, title, completed, solverId, taskId) values (72, 'Multi-Sector Companies', 0, 10, 6);
insert into TaskChecks (id, title, completed, solverId, taskId) values (73, 'Major Banks', 0, 3, 20);
insert into TaskChecks (id, title, completed, solverId, taskId) values (74, 'Electric Utilities: Central', 1, 7, 8);
insert into TaskChecks (id, title, completed, solverId, taskId) values (75, 'Major Pharmaceuticals', 1, 9, 4);
insert into TaskChecks (id, title, completed, solverId, taskId) values (76, 'Specialty Insurers', 1, 5, 8);
insert into TaskChecks (id, title, completed, solverId, taskId) values (77, 'Telecommunications Equipment', 0, 5, 1);
insert into TaskChecks (id, title, completed, solverId, taskId) values (78, 'Electric Utilities: Central', 0, 2, 20);
insert into TaskChecks (id, title, completed, solverId, taskId) values (79, 'Specialty Chemicals', 0, 7, 13);
insert into TaskChecks (id, title, completed, solverId, taskId) values (80, 'n/a', 1, 9, 13);
insert into TaskChecks (id, title, completed, solverId, taskId) values (81, 'Investment Bankers/Brokers/Service', 0, 4, 8);
insert into TaskChecks (id, title, completed, solverId, taskId) values (82, 'Ordnance And Accessories', 0, 9, 5);
insert into TaskChecks (id, title, completed, solverId, taskId) values (83, 'Electric Utilities: Central', 0, 3, 11);
insert into TaskChecks (id, title, completed, solverId, taskId) values (84, 'Multi-Sector Companies', 0, 1, 2);
insert into TaskChecks (id, title, completed, solverId, taskId) values (85, 'Consumer Electronics/Appliances', 1, 8, 11);
insert into TaskChecks (id, title, completed, solverId, taskId) values (86, 'Electrical Products', 1, 5, 15);
insert into TaskChecks (id, title, completed, solverId, taskId) values (87, 'Precious Metals', 1, 8, 20);
insert into TaskChecks (id, title, completed, solverId, taskId) values (88, 'Clothing/Shoe/Accessory Stores', 0, 2, 6);
insert into TaskChecks (id, title, completed, solverId, taskId) values (89, 'EDP Services', 0, 1, 7);
insert into TaskChecks (id, title, completed, solverId, taskId) values (90, 'Farming/Seeds/Milling', 1, 2, 1);
insert into TaskChecks (id, title, completed, solverId, taskId) values (91, 'Television Services', 1, 3, 16);
insert into TaskChecks (id, title, completed, solverId, taskId) values (92, 'Major Pharmaceuticals', 0, 8, 17);
insert into TaskChecks (id, title, completed, solverId, taskId) values (93, 'n/a', 1, 3, 14);
insert into TaskChecks (id, title, completed, solverId, taskId) values (94, 'Semiconductors', 0, 8, 12);
insert into TaskChecks (id, title, completed, solverId, taskId) values (95, 'n/a', 0, 1, 14);
insert into TaskChecks (id, title, completed, solverId, taskId) values (96, 'n/a', 1, 7, 14);
insert into TaskChecks (id, title, completed, solverId, taskId) values (97, 'Clothing/Shoe/Accessory Stores', 1, 9, 17);
insert into TaskChecks (id, title, completed, solverId, taskId) values (98, 'Business Services', 0, 8, 10);
insert into TaskChecks (id, title, completed, solverId, taskId) values (99, 'Business Services', 0, 5, 4);
insert into TaskChecks (id, title, completed, solverId, taskId) values (100, 'Computer Software: Prepackaged Software', 0, 5, 20);

insert into Groups (name) values ('omeprazole');
insert into Groups (name) values ('Artificial Tears');
insert into Groups (name) values ('daytime pe nitetime');
insert into Groups (name) values ('Metoprolol Succinate');
insert into Groups (name) values ('Betaxolol');

insert into UserGroups (groupId, userId) values (3, 1);
insert into UserGroups (groupId, userId) values (3, 18);
insert into UserGroups (groupId, userId) values (1, 1);
insert into UserGroups (groupId, userId) values (3, 6);
insert into UserGroups (groupId, userId) values (2, 15);
insert into UserGroups (groupId, userId) values (3, 3);
insert into UserGroups (groupId, userId) values (5, 8);
insert into UserGroups (groupId, userId) values (1, 10);
insert into UserGroups (groupId, userId) values (5, 13);
insert into UserGroups (groupId, userId) values (1, 3);

insert into ProjectGroups (groupId, projectId) values (1, 1);
insert into ProjectGroups (groupId, projectId) values (5, 2);
insert into ProjectGroups (groupId, projectId) values (2, 3);
insert into ProjectGroups (groupId, projectId) values (5, 7);
insert into ProjectGroups (groupId, projectId) values (5, 5);

insert into ProjectUsers (userId, projectId) values (1, 1);
insert into ProjectUsers (userId, projectId) values (2, 2);
insert into ProjectUsers (userId, projectId) values (3, 3);
insert into ProjectUsers (userId, projectId) values (1, 4);
insert into ProjectUsers (userId, projectId) values (2, 5);