export const routeEnum = Object.freeze({
  HOME: "/",
  LOGIN: "/prihlasit",
  SEARCH: "/hledat",
  PROJECTS: "/projekty",
  PROJECTS_EDIT: "/projekty/upravit/:id",
  PROJECTS_DETAIL: "/projekty/:id",
  PROJECTS_NEW: "/projekty/novy",
  USER_PROFIL: "/profil",
  NOTIFICATIONS: "/oznameni",
  FORGOTTEN_PASSWORD: "/zapomenute-heslo",
  RESET_PASSWORD: "/obnovit-heslo",
  TIME_TRACKS: "/zaznam-casu",
  TIME_TRACKS_REPORT: "/zaznam-casu/report",
  TODO: "/moje-todo",
  ADMIN_CLIENT: "/administrace/klienti",
  ADMIN_GROUP: "/administrace/skupiny",
  ADMIN_USER: "/administrace/uzivatele",
});
