exports.SOCKET_EMIT = Object.freeze({
  TASK_NEW: "TASK_NEW",
  TASK_EDIT: "TASK_EDIT",
  TASK_DELETE: "TASK_DELETE",
  PROJECT_NEW: "PROJECT_NEW",
  PROJECT_EDIT: "PROJECT_EDIT",
  PROJECT_DELETE: "PROJECT_DELETE",
  NOTIFICATION_NEW: "NOTIFICATION_NEW",
});

exports.PROJECT_STATE = Object.freeze({
  STATUS_PLANNED: 1,
  STATUS_ACTIVE: 5,
  STATUS_COMPLETED: 10,
  STATUS_CANCELLED: 20,
});

exports.NOTIFICATION_TYPE = Object.freeze({
  TYPE_TASK: 1,
  TYPE_TASK_COMMENT: 2,
});
